### PR TITLE
Submissions history

### LINKED ISSUE #17: Submissions history for a given exercise
It should be accessible by clicking the exercise name in the guide view.

### PR DESCRIPTION
**Pull request by faloi**
Closes #17 

It's still a work in progress, please comment.

image

image

image

### CODE REVIEW

**Comment by faloi** [comment]
@javifernandes @aguspina @flbulgarelli

**Comment by flbulgarelli** [comment]
Like it!

**Comment by javierfernandes** [comment]
Cool !!

**Comment by aguspina** [comment]
U rock!

**Pull request merged**
